name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - v.*

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: niden/actions-memcached@v7
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.x
      - name: Run tests
        run: make test TEST_FLAGS="-race -tags integration -timeout 5m"
      - name: Check codegen
        run: make check-generated
  e2e-testing:
    runs-on: ubuntu-latest
    needs: unit-testing
    strategy:
      matrix:
        test: ['10_* 11_* 12_*', '13_* 14_* 15_*', '16_* 17_*', '20_* 21_* 22_*']
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.3.0
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.x
      - name: Build containers
        run: make all
      - name: Run tests
        run: |
          E2E_TESTS='${{ matrix.test }}' make e2e-gh
